trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: main

steps:
# Checkout the source code from the Azure DevOps repository
- checkout: self

# Archive the static HTML project files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/html-artifacts.zip'
    replaceExistingArchive: true

# Publish the archived files as build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'html-artifacts'
    publishLocation: 'Container'

# Sync the code from Azure DevOps to GitHub repository
- script: |
    git remote set-url origin https://$(gitUser):$(gitToken)@github.com/ANAND9963/html-css-js-portofolio.git
    git fetch origin main
    git checkout main || git checkout -b main
    git pull origin main --rebase
    git push origin main || echo "Push to GitHub failed."
  displayName: 'Sync to GitHub'
  env:
    gitUser: $(gitUser)  # GitHub username, passed as a pipeline variable
    gitToken: $(gitToken)  # GitHub PAT (personal access token), passed as a secret variable
