trigger:
- preview

pool:
  name: default

steps:
# Checkout the source code from the Azure DevOps repository
- checkout: self

# Archive the static HTML project files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false

# Publish the archived files as build artifacts
- task: PublishBuildArtifacts@1

# Sync the code from Azure DevOps to GitHub repository
- script: |
    git remote add github https://github.com/ANAND9963/html-css-js-portofolio.git
    git pull github main --allow-unrelated-histories
    git push github main
  displayName: 'Sync to GitHub'
