trigger:
  - main

pool:
  name: 'Default'

steps:
# Checkout the source code from the Azure DevOps repository
- checkout: self

# Archive the static HTML project files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false

# Publish the archived files as build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'html-artifacts'
    publishLocation: 'Container'

# Sync the code from Azure DevOps to GitHub repository
- script: |
    git remote add origin https://$(gitUser):$(gitToken)@github.com/ANAND9963/html-css-js-portofolio.git
    git fetch origin main
    git pull origin main 
    git push origin main
  displayName: 'Sync to GitHub'
  env:
    gitUser: $(gitUser)  # GitHub username, passed as a pipeline variable
    gitToken: $(gitToken)  # GitHub PAT (personal access token), passed as a secret variable
  workingDirectory: $(Build.SourcesDirectory)  # Run git commands in the checked-out repository directory
